/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Estructuras;

import javax.swing.JOptionPane;

/**
 *
 * @author Yfmay
 */
public class View extends javax.swing.JFrame {

   private String[] vector;
    private int[][] grafo;
     
    public View(String[] vector, int[][] grafo){
        this.vector = vector;
        initComponents();
        this.grafo = grafo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jplay = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jplay.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jplay.setText("Iniciar");
        jplay.setRequestFocusEnabled(false);
        jplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jplayMouseClicked(evt);
            }
        });
        jplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jplayActionPerformed(evt);
            }
        });
        jPanel1.add(jplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 150, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Estructuras/fondo/grafoEtructuras.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 660, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplayMouseClicked

        CaminoHamiltoniano h = new CaminoHamiltoniano(grafo);
        String opcion = JOptionPane.showInputDialog(this,"Seleccione el pueblo de salida","Pueblos",1,null,vector,vector[0]).toString();
        if(h.encontrarCaminoHamiltoniano(busquedaSecuencial(vector,opcion), vector)){
            JOptionPane.showMessageDialog(this,h.toString(vector) + "\n\n" + h.conLluvia(vector),"Ruta Generada",1);
        }else{
            JOptionPane.showMessageDialog(this, "Los derrumbes ocacionados han impedido la comunicación con todas las ciudades", "Advertencia",2);
        }
        
        
    }//GEN-LAST:event_jplayMouseClicked

    private void jplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jplayActionPerformed

    public int busquedaSecuencial(String[] vector, String x){
        boolean found = false;
        
        for(int i=0; i< vector.length && found==false; i++){
            if(x.equals(vector[i])){
                found = true;
                return i;
            }
        }
        return -1;
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jplay;
    // End of variables declaration//GEN-END:variables
}
